"""Add user_email to AgentToken

Revision ID: 20025ef7fbcc
Revises: 34b44198417b
Create Date: 2025-04-28 14:22:53.547963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20025ef7fbcc'
down_revision: Union[str, None] = '34b44198417b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onebox_tokens', sa.Column('user_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onebox_tokens', 'user_email')
    # ### end Alembic commands ###
